define({
        root: {
                optionsNotIdentified: "The following required options were not identified: ",
                dataNotIdentified: "Data for 'x' or 'y' coordinates could not be identified.",
        },
        // "zh": true,
        // "zh-tw": true,
        // "tr": true,
        // "th": true,
        // "sv": true,
        // "sl": true,
        // "sk": true,
        // "ru": true,
        // "ro": true,
        // "pt": true,
        // "pt-pt": true,
        // "pl": true,
        // "nl": true,
        // "nb": true,
        // "ko": true,
        // "kk": true,
        // "ja": true,
        // "it": true,
        // "hu": true,
        // "he": true,
        "fr": true,
        // "fi": true,
        // "es": true,
        // "el": true,
        // "de": true,
        // "da": true,
        // "cs": true,
        // "ca": true,
        // "ar": true
});